export const AppContent = {
  brand: 'Vue Social',
  ok: 'Ok',
  cancel: 'Cancel',
  signin: 'Sign in',
  signup: 'Sign up',
  rememberMe: 'Remember me',
  loginSubtitle: `If you don't have an account, please click on`,
  signupSubtitle: `If you have an account, please click on`,
  edit: 'Edit',
  delete: 'Delete',
  inactive: 'Inactive',
  active: 'Active',
  areYouSure: "Yes, I'm sure",
  noCancel: 'No, cancel',
  confirmDialogMessage: 'Are you sure you want to delete this post?',
  browse: 'Browse',
  dragDrop: 'Drag and drop files',
  post: 'Post',
  moreThan5Image: 'You can not upload more than 5 files',
  reset: 'Reset',
  reply: 'Replay',
  profile: 'Profile',
  settings: 'Settings',
  logout: 'Logout',
  footerText: 'All rights reserved',
  poweredBy: 'LearnUi',
  poweredByText: 'Powered by',
  poweredByUrl: 'https://www.learnui.com',
  welcomeTitle: 'Welcome to Profiler',
  welcomeContent: `Profiler is a social network site that can be used to connect developers. 
                    use this site for multipurpose social activities like job, videos, learning, 
                    bloging and much more. Now join & connect with cool Developers around the world !!! `,

  authLoginText: "If you don't have an account, please",
  authRegisterText: 'If you have an account, please',
  authForgetText: 'Back to login page, please',
  authEmailVerify: 'Please verify your email',
  appName: 'Profiler',
  authHeading: 'Welcome to Profiler',
  homePageContent: `Profiler is a social network site that can be used to connect developers. 
                    use this site for multipurpose social activities like job, videos, learning, 
                    bloging and much more. Now join & connect with cool Developers around the world !!! `
}
