export const AppContent = {
  brand: 'Vue Social',
  ok: 'Ok',
  cancel: 'Cancel',
  signin: 'Sign in',
  signup: 'Sign up',
  rememberMe: 'Remember me',
  loginSubtitle: `If you don't have an account, please click on`,
  signupSubtitle: `If you have an account, please click on`,
  edit: 'Edit',
  delete: 'Delete',
  inactive: 'Inactive',
  active: 'Active',
  areYouSure: "Yes, I'm sure",
  noCancel: 'No, cancel',
  confirmDialogMessage: 'Are you sure you want to delete this post?',
  browse: 'Browse',
  dragDrop: 'Drag and drop files',
  post: 'Post',
  moreThan5Image: 'You can not upload more than 5 files',
  reset: 'Reset',
  reply: 'Replay',
  profile: 'Profile',
  settings: 'Settings',
  logout: 'Logout'
}
